const fs = require('fs');
let f = fs.readFileSync('backend/src/controllers/lpController.js', 'utf8');

const oldHtml = `const html = \`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Stamped!</title><style>body{background:#0a0a0a;color:#fff;font-family:sans-serif;display:flex;align-items:center;justify-content:center;min-height:100vh;text-align:center;padding:24px}h1{font-size:1.8rem;margin:12px 0 8px}p{color:rgba(255,255,255,0.6);font-size:.9rem}.dots{margin:20px 0;line-height:2}</style></head><body><div><div style="font-size:3.5rem">\${rewardReady ? '🎉' : '✅'}</div><h1>\${rewardReady ? 'Reward ready!' : 'Stamp added!'}</h1><p>\${rewardReady ? 'Show this to the staff to claim your ' + rewardName : newCount + ' of ' + goal + ' stamps'}</p><div class="dots">\${dots}</div>\${rewardReady ? '<p style="color:#22c55e;font-weight:700;font-size:1.1rem">Show your wallet pass to redeem</p>' : '<p style="color:rgba(255,255,255,0.4);font-size:.8rem">' + (goal - newCount) + ' more stamp' + (goal - newCount !== 1 ? 's' : '') + ' until your ' + rewardName + '</p>'}<a href="/lp/\${slug}" style="display:inline-block;margin-top:20px;padding:10px 24px;background:rgba(255,255,255,0.1);color:#fff;border-radius:10px;text-decoration:none;font-size:.85rem">View your pass</a></div></body></html>\``;

const newHtml = `const html = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Stamped!</title><style>*{box-sizing:border-box;margin:0;padding:0}body{background:#0a0a0a;color:#fff;font-family:-apple-system,BlinkMacSystemFont,sans-serif;display:flex;align-items:center;justify-content:center;min-height:100vh;text-align:center;padding:24px;overflow:hidden}.wrap{position:relative;z-index:1}.emoji{font-size:4rem;animation:pop 0.4s cubic-bezier(0.175,0.885,0.32,1.275)}h1{font-size:1.8rem;margin:12px 0 8px;font-weight:800}p{color:rgba(255,255,255,0.6);font-size:.9rem;margin:6px 0}.dots{margin:20px 0;line-height:2}.confetti-piece{position:fixed;width:10px;height:10px;border-radius:2px;animation:fall linear forwards}@keyframes pop{0%{transform:scale(0)}70%{transform:scale(1.2)}100%{transform:scale(1)}}@keyframes fall{0%{transform:translateY(-20px) rotate(0deg);opacity:1}100%{transform:translateY(110vh) rotate(720deg);opacity:0}}</style></head><body><div class="wrap"><div class="emoji">' + (rewardReady ? "🎉" : "✅") + '</div><h1>' + (rewardReady ? "Reward ready!" : "Stamp added!") + '</h1><p>' + (rewardReady ? "Show your pass to claim your " + rewardName : newCount + " of " + goal + " stamps collected") + '</p><div class="dots">' + dots + '</div>' + (rewardReady ? '<p style="color:#22c55e;font-weight:700;font-size:1.1rem;margin-top:12px">Show your wallet pass to redeem</p>' : '<p style="color:rgba(255,255,255,0.4);font-size:.8rem;margin-top:8px">' + (goal - newCount) + ' more stamp' + (goal - newCount !== 1 ? "s" : "") + " until your " + rewardName + "</p>") + '<a href="/lp/' + slug + '" style="display:inline-block;margin-top:20px;padding:10px 24px;background:rgba(255,255,255,0.1);color:#fff;border-radius:10px;text-decoration:none;font-size:.85rem">View your pass</a></div><script>var colors=["#ff5a1f","#22c55e","#3b82f6","#f59e0b","#ec4899","#8b5cf6","#06b6d4"];for(var i=0;i<80;i++){var c=document.createElement("div");c.className="confetti-piece";c.style.cssText="left:"+Math.random()*100+"vw;top:-20px;background:"+colors[Math.floor(Math.random()*colors.length)]+";width:"+(6+Math.random()*8)+"px;height:"+(6+Math.random()*8)+"px;border-radius:"+(Math.random()>0.5?"50%":"2px")+";animation-duration:"+(1.5+Math.random()*2)+"s;animation-delay:"+(Math.random()*0.8)+"s;";document.body.appendChild(c);}setTimeout(function(){document.querySelectorAll(".confetti-piece").forEach(function(el){el.remove();});},4000);<\/script></body></html>'`;

if (f.includes(oldHtml)) {
  f = f.replace(oldHtml, newHtml);
  console.log('Replaced OK');
} else {
  console.log('NOT FOUND - trying partial match');
  console.log(f.includes('Stamp added!'));
}
fs.writeFileSync('backend/src/controllers/lpController.js', f);
