const fs=require('fs');
let fe=fs.readFileSync('frontend/public/smart-qr-detail.html','utf8').replace(/\r\n/g,'\n');
const infoTab=fs.readFileSync('info_tab.txt','utf8').trimEnd();
const infoIIFE=fs.readFileSync('info_iife.tmp','utf8');
const infoDraft=fs.readFileSync('info_draft.txt','utf8');
const mEnd='Info editing coming in next step';
const mStart='<div class="sqd-tab-panel" data-panel="info"';
const s=fe.lastIndexOf(mStart,fe.indexOf(mEnd));
const e=fe.indexOf('</div>',fe.indexOf(mEnd))+6;
if(s>0&&e>s){fe=fe.slice(0,s)+infoTab+'\n'+fe.slice(e+1);console.log('1 done');}else console.log('1 FAIL s='+s+' e='+e);
const m2='  window.renderFeaturedFn = renderFeatured;\n\n})();';
if(fe.includes(m2)){fe=fe.replace(m2,m2+'\n\n'+infoIIFE);console.log('2 done');}else console.log('2 FAIL');
const m3='var featCards = Array.isArray(sec.featured) ? sec.featured : [];';
if(fe.includes(m3)){fe=fe.replace(m3,m3+'\n    var si = sec.info || {};');console.log('3 done');}else console.log('3 FAIL');
const m4='      footer: footer.enabled !== false';
if(fe.includes(m4)){fe=fe.replace(m4,infoDraft+'      footer: footer.enabled !== false');console.log('4 done');}else console.log('4 FAIL');
const o5="    var _ord = order.map(function(k){ return sections[k] || ''; });\n    if (!order.includes('featured')) { var _fbi=order.indexOf('loop'); _ord.splice(_fbi!==-1?_fbi+1:_ord.length-1,0,sections.featured||''); }\n    var body = _ord.join('');";
const n5="    var _ord = order.map(function(k){ return sections[k] || ''; });\n    var _fi2=-1; if (!order.includes('featured')) { var _fbi=order.indexOf('loop'); _fi2=_fbi!==-1?_fbi+1:_ord.length-1; _ord.splice(_fi2,0,sections.featured||''); } else { _fi2=order.indexOf('featured'); }\n    if (!order.includes('info')) { _ord.splice(_fi2+1,0,sections.info||''); }\n    var body = _ord.join('');";
if(fe.includes(o5)){fe=fe.replace(o5,n5);console.log('5 done');}else console.log('5 FAIL: '+JSON.stringify(fe.slice(fe.indexOf('_ord = order.map'),fe.indexOf('_ord = order.map')+80)));
fs.writeFileSync('frontend/public/smart-qr-detail.html',fe,'utf8');
console.log('FE: tab='+fe.includes('info-input-address')+' iife='+fe.includes('ensureInfo')+' ord='+fe.includes('sections.info'));
